### ISSUE TITLE
jail + ce image

### ISSUE THREAD

**Issue by kaspar-allenbach** [easy-designs/easy_jail.ee_addon#1]
Hi. I'm triyng out this jail thing. Its great so far.

One question tough:

I wrap a ce image tag inside jail.
This works perfectly. But I have one issue with the css class:

```
{exp:easy_jail:prep}
    {exp:ce_img:single src="{produkte_icon}" class="img-responsive" save_type="png"}
{/exp:easy_jail:prep}
```

This results in:

```
<img class="jail" src="/images/made/images/uploads/content_images/icon-dataset_270_270.png" style="display: inline;">
<noscript>
  <img src="/images/made/images/uploads/content_images/icon-dataset_270_270.png" class="img-responsive" width="270" height="270" alt=""/>
</noscript>
```

Is it possible to append the class "img-responsive" class on the img tag outside noscript and not just inside the noscript tag?

**Comment by aarongustafson** [comment]
I’m currently traveling, but let me see what I can do when I get a moment
to sit down & look at it. Shouldn’t be hard.

**Comment by kaspar-allenbach** [comment]
Is this plugin dead?

Jail also swallows the alt tag:

```
{exp:easy_jail:prep}
   {exp:ce_img:single src="{produkte_icon}" attributes='alt="The Cow"'}
{/exp:easy_jail:prep}
```

results in 

```
<img class="jail" src="bla.jpg" alt="" style="display: inline;">
<noscript>
     <img src="bla.jpg" alt="">
</noscript>
```

**Comment by aarongustafson** [comment]
Hmm, that’s not right. I will look into that today.

**Comment by kaspar-allenbach** [comment]
Hi. Did you have time to look into it?

**Comment by aarongustafson** [comment]
The `alt` fix is in. (I apologize, I got insanely busy.)

I will work on the other fix for appending the `class` too.

**Comment by aarongustafson** [comment]
Should be good now. Give it a shot.
