### ISSUE TITLE
Reload page

### ISSUE THREAD

**Issue by kaspar-allenbach** [easy-designs/easy_jail.ee_addon#2]
One other thing.

When I relaod the page the images are hidden until I scroll a bit. Why is that?

The jail plugin also doesn't work when the image is inside a bootrstrap modal window.

**Comment by kaspar-allenbach** [comment]
I found a solution.
After: 
`{exp:easy_jail:js config="{offset:300}"}`

I write a window.resize

```
<script>
$(function(){
    $('img.jail').jail();
        window.onload = function() {
        $(window).resize()};
    });
</script>
```

This way the images appear instantly and not on scroll.

**Comment by aarongustafson** [comment]
Finally incorporated this fix. Thank you.

**Comment by aarongustafson** [comment]
Closing.
